Fix issue #2292
polybar/polybar pull request #2306
Opened 2020-12-15 17:43 UTC by Filip62

## What type of PR is this? (check all applicable)

* [ ] Refactor
* [ ] Feature
* [X] Bug Fix
* [ ] Optimization
* [ ] Documentation Update
* [ ] Other: *Replace this with a description of the type of this PR*

## Description

## Related Issues & Documents

Fixes [#2292](https://github.com/polybar/polybar/issues/2292)
## Documentation (check all applicable)

* [ ] This PR requires changes to the Wiki documentation (describe the changes)
* [ ] This PR requires changes to the documentation inside the git repo (please add them to the PR).
* [x] Does not require documentation changes

2020-12-15 22:59 UTC, patrick96 requested changes
Thanks for looking into this.

I think this solution only works if all of the indicators are empty (`enabled == 0`)

For example, imagine `m_indicators` had three elements and only the second element was empty, in that case `build` would return true but the output would be:

```
label1__label2
```

(Each underscore represents a call to `builder->space`).
Here, returning false would also not fix this because only trailing spaces are removed by the `get_output` function in `base.inl`.

This is a tricky problem. One solution I could think of is to first iterate over all indicators and add all non-empty labels to a separate vector. We can then iterate over that vector and always add spacing between labels because we know they're not empty.

I think there are also ways to do this in a single iteration but they will probably be a lot more complex than what I described because you have to deal with situations like two consecutive labels being empty.

Also, generally the check for a label being empty is `!label || !*label`, since we know `indicator.second` actually is a valid pointer, you can just use `!*indicator.second` to check if a label is empty.

2020-12-16 17:55 UTC, Filip62 commented
Actually I think it works.

My initial problem was that a trailing space was added between `<label-layout>` and `<label-indicators>` because even though the indicator was empty, the method `xkeyboard::build` returned `true`, therefore the trailing space was not removed.

Now if at least one of the indicators is not empty only then will `xkeyboard::build` return true, so the space makes sense in that scenario.

I think the calls to `builder->space` work just as expected.
`label-indicator-margin = 1`
![0](https://user-images.githubusercontent.com/58399088/102386319-3b43a080-3fcf-11eb-81ac-800edf816d63.png)
![1](https://user-images.githubusercontent.com/58399088/102386329-3e3e9100-3fcf-11eb-955f-6d533f156c90.png)
![2](https://user-images.githubusercontent.com/58399088/102386342-40a0eb00-3fcf-11eb-8099-55b19e4976b8.png)
![3](https://user-images.githubusercontent.com/58399088/102386350-426aae80-3fcf-11eb-9889-dd06e9d3c77d.png)
![2alt](https://user-images.githubusercontent.com/58399088/102386597-8958a400-3fcf-11eb-8f1e-f3b0e30974a1.png)

In the current master branch there would be a trailing space at the end of every screenshot.

2020-12-17 01:17 UTC, patrick96 requested changes
I think there was a misunderstading on my part as to what went wrong in your issue.

The extra space(s) after `<label-layout>` can come from one of two places (or both):

* `format-spacing`
* The fact that the format is set to `format = <label-layout> <label-indicator>`

I originally thought your issue was caused by the first, but it isn't because `format-spacing` defaults to 0, so no spacing is added in your case.

You are actually experiencing the second one and you are completely correct that the `build` function returned `true` even though no indicators were present and it should have returned false.

If `format-spacing` is set to anything other than 0, you still get extra spacing. If you want to, you can of course also tackle that, but I think we can just merge the fix for the issue with the wrong return value.

Could you please also add this fix to the `CHANGELOG.md` file. We have just today started keeping a changelog as we merge stuff, there is a new section about in [`CONTRIBUTING.md`](https://github.com/polybar/polybar/blob/master/CONTRIBUTING.md#changelog)

Also `!indicator.second` will always return `false` because this only checks if the pointer actually exists and not if the underlying label is empty, that's why you need `*indicator.second`. Right now the `build` function always returns false because `enabled` is never incremented.
That's also why you *never* get any space after the module even though you set `label-indicator-margin = 1`.
margin is always supposed to be added to both sides of a label (or format) and should never be trimmed.

2020-12-17 01:17 UTC, patrick96 commented on src/modules/xkeyboard.cpp
> +        if (!indicator.second) {
```suggestion
        if (!*indicator.second) {
```

2020-12-17 01:17 UTC, patrick96 commented on src/modules/xkeyboard.cpp
> +      return enabled > 0 && n > 0;
```suggestion
      return enabled > 0;
```

`n` is always greater or equal to `enabled`

2020-12-17 19:00 UTC, Filip62 commented
@patrick96 I think I fixed both issues.
From what I tested, everything worked as I would expect.
I hope it works because the solution feels pretty nice with my lame skills. :)

2020-12-17 19:45 UTC, patrick96 approved these changes
Oh wow. I was sure that the solution must be more complex, but this does indeed work. Good job!

2020-12-17 19:49 UTC, merged