feat(conf) always show urgent workspaces in i3
polybar/polybar pull request #2378
Opened 2021-02-14 04:38 UTC by zappolowski

## What type of PR is this? (check all applicable)

* [ ] Refactor
* [x] Feature
* [ ] Bug Fix
* [ ] Optimization
* [ ] Documentation Update
* [ ] Other: *Replace this with a description of the type of this PR*

## Description

Given `pin-workspaces = true`, setting `show-urgent = true` will show urgent workspaces on the current bar even when the workspace is not associated with the current monitor. If `pin-workspaces = false`, this option has no effect.

## Related Issues & Documents

Closes #2374 

## Documentation (check all applicable)

* [x] This PR requires changes to the Wiki documentation (describe the changes)
* [ ] This PR requires changes to the documentation inside the git repo (please add them to the PR).
* [ ] Does not require documentation changes

```patch
--- wiki.old	2021-02-14 05:34:34.898430279 +0100
+++ wiki.new	2021-02-14 05:37:25.829103300 +0100
@@ -34,6 +34,16 @@
 ; Default: false
 pin-workspaces = true
 
+; Show workspaces having the urgent hint set in the bar
+; regardless of the workspace being on the current output
+; or not.
+;
+; This option only makes sense in when pin-workspaces is
+; enabled.
+;
+; Default: false
+show-urgent = true
+
 ; This will split the workspace name on ':'
 ; Default: false
 strip-wsnumbers = true
```

2021-02-14 20:30 UTC, patrick96 requested changes
Good job!

Please also add an entry to the changelog: https://github.com/polybar/polybar/blob/master/CONTRIBUTING.md#changelog

2021-02-15 19:22 UTC, zappolowski commented
Amended to the commit.

2021-02-15 20:18 UTC, patrick96 requested changes
Just a small wording change. We can merge after this.

2021-02-15 20:18 UTC, patrick96 commented on CHANGELOG.md
> +  ([`2374`](https://github.com/polybar/polybar/issues/2374))
```suggestion
- Option to always show urgent windows in i3 module when `pin-workspace` is active
  ([`2374`](https://github.com/polybar/polybar/issues/2374))
```

2021-02-15 20:31 UTC, patrick96 approved these changes

2021-02-15 20:31 UTC, merged

2021-02-15 20:31 UTC, patrick96 commented
Thanks! :rocket: