Universal Visibility Action (#2320 cont'd)
polybar/polybar pull request #2426
Opened 2021-05-09 23:21 UTC by parmort

## What type of PR is this? (check all applicable)

* [X] Refactor
* [X] Feature
* [ ] Bug Fix
* [ ] Optimization
* [ ] Documentation Update
* [ ] Other: *Replace this with a description of the type of this PR*

## Description
Adds universal module visibility control actions `toggle_visible`, `set_visible`, and `set_invisible`.

## Related Issues & Documents
#2108
#2320
#2342 

## Documentation (check all applicable)

* [X] This PR requires changes to the Wiki documentation (describe the changes)
* [ ] This PR requires changes to the documentation inside the git repo (please add them to the PR).
* [ ] Does not require documentation changes

2021-05-10 01:19 UTC, patrick96 commented
Nice :smiley: 

I don't really have time to review right now, I got a lot going on. It's gonna be at least a few weeks until I get to this.

2021-06-28 09:50 UTC, patrick96 requested changes
Looks good!

This change does also require documentation in `doc/user/actions.rst`. I would say we add a new subsection to "Available Actions" named "All modules" at the beginning, just before the date module.

Also, maybe we should, just by convention, have a `module_` prefix for all global module actions to prevent future naming conflicts.
To be consistent with the command names to change bar visibility, we could use the names `module_toggle`, `module_show`, `module_hide`. What do you think?

2021-06-28 09:50 UTC, patrick96 commented on include/modules/meta/base.inl
> +    // m_log.info("%s: Visibility changed (state=%s)", m_name, value ? "shown" : "hidden");
```suggestion
    m_log.info("%s: Visibility changed (state=%s)", m_name, value ? "shown" : "hidden");
```

2021-07-06 18:32 UTC, parmort commented
> To be consistent with the command names to change bar visibility, we could use the names `module_toggle`, `module_show`, `module_hide`. What do you think?

Yeah, that sounds like a good idea. I remember not being sure what to call them. I'll get the changes up in a few minutes.

2021-07-07 19:43 UTC, patrick96 approved these changes
Looks good now!

2021-07-07 19:43 UTC, merged