feat:add tokens to display memory in MiB when GiB val <= 1.0 (#2472)
polybar/polybar pull request #2488
Opened 2021-09-03 08:43 UTC by malta895

## What type of PR is this? (check all applicable)

* [ ] Refactor
* [X] Feature
* [ ] Bug Fix
* [ ] Optimization
* [ ] Documentation Update
* [ ] Other: *Replace this with a description of the type of this PR*

## Description

Memory/swap values can now be displayed in MiB instead of GiB when the value is less than 1 GiB, for better precision.
For example, display 512 MiB instead of 0.50 GiB.

The following tokens have been added to the memory module in order to activate this behavior from config:
```
;   %used%
;   %free%
;   %total%
;   %swap_total%
;   %swap_free%
;   %swap_used%
```

## Related Issues & Documents

Closes #2472 

## Documentation (check all applicable)

* [X] This PR requires changes to the Wiki documentation (describe the changes)
* [ ] This PR requires changes to the documentation inside the git repo (please add them to the PR).
* [ ] Does not require documentation changes

The documentation of the memory module should be updated with the tokens described earlier, and a description on their behavior.

2021-09-03 19:57 UTC, patrick96 requested changes
Very nice! Thanks a lot for helping out :smiley: 

Please also add these changes to the `CHANGELOG.md` file in the `Added` section. Also see the relevant section in [CONTRIBUTING.md](https://github.com/polybar/polybar/blob/master/CONTRIBUTING.md#changelog) for more info.

2021-09-03 19:57 UTC, patrick96 commented on src/utils/string.cpp
> +  string filesize_gib_mib(unsigned long long kibibytes, size_t precision, const string& locale) {
I don't think when using MB, it should display anything after the decimal point (just as it already does with the `%mb_*%` tokens). Either have two `precision` arguments, one for MB and one for GB or just always use `0` for the precision when using MB.

2021-09-03 19:57 UTC, patrick96 commented on src/utils/string.cpp
> +    if(kibibytes / 1024.0 / 1024.0 < 1.0) {
```suggestion
    if(kibibytes  < 1024 * 1024) {
```

2021-09-03 20:24 UTC, malta895 commented
> Please also add these changes to the `CHANGELOG.md` file in the `Added` section. Also see the relevant section in [CONTRIBUTING.md](https://github.com/polybar/polybar/blob/master/CONTRIBUTING.md#changelog) for more info.

Done! Sorry I missed that part of contributing :sweat_smile:

2021-09-04 11:07 UTC, patrick96 commented on CHANGELOG.md
> +  ([`2472`](https://github.com/polybar/polybar/issues/2472))
```suggestion
- `internal/memory`: New tokens `%used%`, `%free%`, `%total%`, `%swap_total%`, 
  `%swap_free%`, and `%swap_used%` that automatically switch between MiB and GiB
  when below or above 1GiB.
  ([`2472`](https://github.com/polybar/polybar/issues/2472))
```

2021-09-04 11:07 UTC, patrick96 commented on src/modules/memory.cpp
> + #include <iomanip>
```suggestion
#include <iomanip>
```

2021-09-04 11:08 UTC, patrick96 commented
Looks good now :)

I also changed some small things myself, will merge this once CI is done.

2021-09-04 11:08 UTC, patrick96 approved these changes

2021-09-04 11:14 UTC, merged