feat(pulseaudio): define invert-scroll option
polybar/polybar pull request #2664
Opened 2022-03-24 10:29 UTC by itsfarseen

## What type of PR is this? (check all applicable)

* [ ] Refactor
* [X] Feature
* [ ] Bug Fix
* [ ] Optimization
* [ ] Documentation Update
* [ ] Other: *Replace this with a description of the type of this PR*

## Description
When we enable natural scrolling option in libinput, it sends scroll down even when we swipe up on the touchpad.  
This makes the pulseaudio module feel weird.  
This option fixes that.

## Related Issues & Documents

## Documentation (check all applicable)

* [X] This PR requires changes to the Wiki documentation (describe the changes)
* [ ] This PR requires changes to the documentation inside the git repo (please add them to the PR).
* [ ] Does not require documentation changes

Add the following to the wiki under Pulseaudio:

```ini
invert-scroll = false; # Reverses the increment/decrement on scroll event. Set this to true if you are using natural scrolling option on your touchpad.
```

2022-03-24 12:33 UTC, patrick96 requested changes
Nice. I didn't know that that's how natural scrolling was implemented, but that actually makes a lot of sense.

Please also add your changes to the changelog: https://github.com/polybar/polybar/blob/master/CONTRIBUTING.md#changelog

2022-03-24 12:33 UTC, patrick96 commented on src/modules/pulseaudio.cpp
> +    m_invert_scroll = m_conf.get(name(), "invert-scroll", false);
Please call the option `reverse-scroll` to be consistent with other modules that also have such an option.

2022-03-27 16:36 UTC, itsfarseen commented
@patrick96, I have renamed the field and added changelog entry.

2022-04-02 21:28 UTC, patrick96 approved these changes
Looks good now, thanks!

I went a head and resolved the merge conflicts.

2022-04-02 21:45 UTC, merged