auto-detect default backlight
polybar/polybar pull request #2728
Opened 2022-05-23 13:57 UTC by raffael0

## What type of PR is this? (check all applicable)

* [ ] Refactor
* [x] Feature
* [ ] Bug Fix
* [ ] Optimization
* [ ] Documentation Update
* [ ] Other: *Replace this with a description of the type of this PR*

## Description
Implements the automatic detection of cards for the backlight module(See #2572)
When no `card` is specified, the backlight module looks for a viable card  in `/sys/class/backlight/` and uses that.
## Related Issues & Documents
Implements part of  #2572 

## Documentation (check all applicable)

* [x] This PR requires changes to the Wiki documentation (describe the changes)
* [ ] This PR requires changes to the documentation inside the git repo (please add them to the PR).
* [ ] Does not require documentation changes
in modules:backlight the following lines should be changed from: 
```
; Use the following command to list available cards:
; $ ls -1 /sys/class/backlight/
card = intel_backlight
```
to:
```
; Use the following command to list available cards:
; $ ls -1 /sys/class/backlight/
; Default: first usable card in /sys/class/backlight
card = intel_backlight
```

2022-06-14 13:25 UTC, patrick96 requested changes
Looks good, thanks!

Just some minor comments.

2022-06-14 13:25 UTC, patrick96 commented on src/modules/backlight.cpp
> +    } catch (const key_error& err) {
We don't need a try-catch here. We can just use the empty string as a default.

2022-06-15 14:22 UTC, patrick96 requested changes

2022-06-15 14:22 UTC, patrick96 commented on src/modules/backlight.cpp
> +    string card = m_conf.get(name(), "card");
```suggestion
    auto card = m_conf.get(name(), "card", ""s);
```

We need a default value here

2022-06-16 10:49 UTC, patrick96 approved these changes
I went ahead and fixed the changelog formatting. Everything looks good now!

2022-06-16 10:51 UTC, raffael0 commented
Thanks! No idea how that always keeps happening. Must be some IDE thing

2022-06-16 10:54 UTC, patrick96 commented
Yeah, many IDEs do auto-formatting on save.

2022-06-16 10:54 UTC, merged

2022-07-20 08:20 UTC, mrquincle commented
Super neat. On my system it all the time switches from `amdgpu_bl0` to `amdgpu_bl1`, so this would be a time-saver.