feat(battery): add ramp-charging tag
polybar/polybar pull request #3172
Opened 2024-10-06 21:27 UTC by stringlapse

## What type of PR is this? (check all applicable)

* [ ] Refactor
* [X] Feature
* [ ] Bug Fix
* [ ] Optimization
* [ ] Documentation Update
* [ ] Other: *Replace this with a description of the type of this PR*

## Description

Added ramp-charging tag to allow for separate icons to be used when charging and discharging. This has been requested a few times over the years but hasn't been added due to the future plans to significantly expand the ramp system (#1752). I wrote this change about a year ago for my own personal use but figured I should submit a pr so others can use it too.

## Related Issues & Documents

Related issues that are already closed:
#1819
#2254
#2503

## Documentation (check all applicable)

* [X] This PR requires changes to the Wiki documentation (describe the changes)
* [ ] This PR requires changes to the documentation inside the git repo (please add them to the PR).
* [ ] Does not require documentation changes

This PR adds a new tag to the battery module. The new tag is named `ramp-charging` and its usage is identical to `ramp-capacity`

2024-10-13 12:08 UTC, patrick96 requested changes
Changes look good. Just a backwards compatibility note, but after that we can merge this.

Please also add a [changelog entry](https://github.com/polybar/polybar/blob/master/CONTRIBUTING.md#changelog) for this.

2024-10-13 12:08 UTC, patrick96 commented on src/modules/battery.cpp
> +        {TAG_BAR_CAPACITY, TAG_RAMP_CHARGING, TAG_ANIMATION_CHARGING, TAG_LABEL_CHARGING});
`TAG_RAMP_CAPACITY` should still be kept here. Otherwise all configs using it will break

2024-10-18 03:40 UTC, stringlapse commented
Oversight fixed and changelog entry added :)

2024-10-19 15:34 UTC, patrick96 approved these changes

2024-10-19 15:34 UTC, merged

2024-10-19 15:34 UTC, patrick96 commented
Thanks :)